<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Entities\Comment.cs" />
    <Compile Remove="Entities\ComplaintHistory.cs" />
    <Compile Remove="Entities\Role.cs" />
    <Compile Remove="Entities\Status.cs" />
    <Compile Remove="Entities\User.cs" />
    <Compile Remove="Entities\UserProfile.cs" />
    <Compile Remove="Entities\UserRole.cs" />
  </ItemGroup>

</Project>
